apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: app-frontend-svc
  namespace: bluegreen-ns
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  selector:
    app: web-frontend
    env: original
  type: NodePort
status:
  loadBalancer: {}
